version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_NAME=taskflow
      - MONGO_URI=mongodb://db:27017/taskflow
    depends_on:
      - db

  db:
    image: mongo:3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=""
      - MONGO_INITDB_DATABASE=taskflow
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
